### ISSUE TITLE
Bibliography TODO

### ISSUE THREAD

**Issue by muziejus** [un-silencing-slavery-at-rose-hall/project-website#3]
- [x] make one
- [ ] Paste in word doc just so something is there
- [x] Loop Alex in on Zotero folder so he can help process remaining items.

**Comment by elotroalex** [comment]
@muziejus waiting for Zotero access

**Comment by elotroalex** [comment]
@muziejus  got the zotero access. now waiting for the doc that has the unprocessed stuff.

**Comment by elotroalex** [comment]
Done and done. Most of it was done as an export from Zotero. I touched the "online sources" so that links would be attached to titles.
