### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by muziejus** [un-silencing-slavery-at-rose-hall/project-website#9]
- [ ] Add SEO and general metadata. Done by editing `app/index.html`
- [x] Look into dynamic titling and reflecting that in og tags.

**Comment by muziejus** [comment]
(Un)Silencing Slavery at Rose Hall



meta description: "The (Un)Silencing Slavery at Rose Hall Project respectfully and lovingly remembers and holds space for the enslaved Africans and their enslaved African-born and Caribbean-born descendants who lived and labored at Rose Hall Plantation in Jamaica.

Remembering the enslaved persons

A digital representation of the 208 

Telling Truths About Rose Hall Plantation, Jamaica

**Comment by muziejus** [comment]
https://github.com/shipshapecode/ember-meta

**Comment by muziejus** [comment]
I've set a title for everything and there's a global `siteTitle` and `description`.

image, jsonld stuff, etc., still needs to be added.

also dublin core.

**Comment by elotroalex** [comment]
all that good stuff is built-in into their head.bs. imma try to load that in now

**Comment by elotroalex** [comment]
ok. ember-meta seems to come with all the meta we will ever need

**Comment by elotroalex** [comment]
jsonld is overkill imho
